PHASE_AWAITING_INPUT = "awaiting_input"
PHASE_FILLING_COMMAND_FORM = "filling_command_form"
PHASE_FILLING_TOOL_FORM = "filling_tool_form"
PHASE_PARSING_ATTACHMENT = "parsing_attachment"
PHASE_APPROVING_REQUEST = "approving_request"
PHASE_CALLING_TOOL = "calling_tool"
PHASE_CALLING_COMMAND = "calling_command"

BASE_PHASE = PHASE_AWAITING_INPUT
FORM_PHASES = {PHASE_FILLING_COMMAND_FORM, PHASE_FILLING_TOOL_FORM}
BUSY_PHASES = {PHASE_PARSING_ATTACHMENT, PHASE_CALLING_TOOL, PHASE_CALLING_COMMAND}
PHASES = (
    PHASE_AWAITING_INPUT,
    PHASE_FILLING_COMMAND_FORM,
    PHASE_FILLING_TOOL_FORM,
    PHASE_PARSING_ATTACHMENT,
    PHASE_APPROVING_REQUEST,
    PHASE_CALLING_TOOL,
    PHASE_CALLING_COMMAND,
)
